version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test_local:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Install necessary system dependencies for browsers
          command: sudo apt-get update && sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 libxt6 libasound2
      - run:
          name: Install Robot Framework and SeleniumLibrary
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Local Chrome"
          command: |
            mkdir -p results/local
            robot -v BROWSER:Chrome -d results/local tests/
      - store_artifacts:
          path: results/local/chrome
          destination: test-reports/local/chrome

  test_remote:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Robot Framework and SeleniumLibrary
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on BrowserStack Remote Browsers - Chrome"
          command: |
            mkdir -p results/remote/chrome
            export BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME
            export BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY
            robot -v BROWSER:Chrome -v REMOTE_URL:https://${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}@hub-cloud.browserstack.com/wd/hub -d results/remote/chrome tests/
      - store_artifacts:
          path: results/remote/chrome
          destination: test-reports/remote/chrome
      - run:
          name: "Run Tests on BrowserStack Remote Browsers - Firefox"
          command: |
            mkdir -p results/remote/firefox
            export BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME
            export BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY
            robot -v BROWSER:Firefox -v REMOTE_URL:https://${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}@hub-cloud.browserstack.com/wd/hub -d results/remote/firefox tests/
      - store_artifacts:
          path: results/remote/firefox
          destination: test-reports/remote/firefox
      - run:
          name: "Run Tests on BrowserStack Remote Browsers - Edge"
          command: |
            mkdir -p results/remote/edge
            export BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME
            export BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY
            robot -v BROWSER:Edge -v REMOTE_URL:https://${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}@hub-cloud.browserstack.com/wd/hub -d results/remote/edge tests/
      - store_artifacts:
          path: results/remote/edge
          destination: test-reports/remote/edge
      - run:
          name: "Run Tests on BrowserStack Remote Browsers - Opera"
          command: |
            mkdir -p results/remote/opera
            export BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME
            export BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY
            robot -v BROWSER:Opera -v REMOTE_URL:https://${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}@hub-cloud.browserstack.com/wd/hub -d results/remote/opera tests/
      - store_artifacts:
          path: results/remote/opera
          destination: test-reports/remote/opera

  test_mac:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: Install Robot Framework and SeleniumLibrary
          command: |
            pip3 install robotframework robotframework-seleniumlibrary selenium
      - run:
          name: Enable SafariDriver
          command: |
            sudo safaridriver --enable
      - run:
          name: Enable Safari Remote Automation
          command: |
            osascript enable_safari_automation.applescript
      - run:
          name: "Run Tests on Safari-Browser (MAC)"
          command: |
            robot -v BROWSER:Safari -d results/safari tests/
      - store_artifacts:
          path: results/safari
          destination: test-reports

#  store_artifacts:
#    docker:
#      - image: cimg/python:3.9
#    steps:
#      - checkout
#      - attach_workspace:
#          at: /tmp/workspace
#      - store_artifacts:
#          path: results
#          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - test_local
      - test_remote
      #- test_mac
      #- store_artifacts:
      #    requires:
      #      - test_local
      #      - test_remote
