version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test_local:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Install necessary system dependencies for browsers
          command: sudo apt-get update && sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 libxt6 libasound2
      - run:
          name: Install Robot Framework and SeleniumLibrary
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Local Chrome"
          command: |
            mkdir -p results/local
            robot -v BROWSER:Chrome -d results/local tests/
      - store_artifacts:
          path: results/local
          destination: test-reports/local

  test_remote:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Install necessary system dependencies for browsers
          command: sudo apt-get update && sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 libxt6 libasound2
      - run:
          name: Install Opera and OperaDriver
          command: |
            wget -q -O operadriver.zip https://github.com/operasoftware/operachromiumdriver/releases/download/v.104.0.5112.81/operadriver_linux64.zip
            unzip operadriver.zip -d operadriver
            sudo mv operadriver/operadriver /usr/local/bin/
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository 'deb https://deb.opera.com/opera-stable/ stable non-free'
            wget -qO- https://deb.opera.com/archive.key | sudo apt-key add -
            sudo apt-get update
            sudo apt-get install -y opera-stable
      - run:
          name: Install Robot Framework and SeleniumLibrary
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Multiple Remote Browsers"
          command: |
            robot -v BROWSER:Chrome -d results/remote tests/
            robot -v BROWSER:Firefox -d results/remote tests/
            robot -v BROWSER:Opera -d results/remote tests/
            robot -v BROWSER:Edge -d results/remote tests/
            robot -v BROWSER:Safari -d results/remote tests/
      - store_artifacts:
          path: results/remote
          destination: test-reports

  store_artifacts:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: results
          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - test_local
      - test_remote
      - store_artifacts:
          requires:
            - test_local
            - test_remote
