version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  setup:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            pip install robotframework
            pip install robotframework-seleniumlibrary
            pip install chromedriver-autoinstaller
            chromedriver-autoinstaller install

  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            robot -d results tests/
      - store_artifacts:
          path: results
          destination: test-results

  test_remote:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install BrowserStack Local
          command: |
            wget https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
            unzip BrowserStackLocal-linux-x64.zip
            mv BrowserStackLocal /usr/local/bin/BrowserStackLocal
      - run:
          name: Start BrowserStack Local
          background: true
          command: |
            BrowserStackLocal $BROWSERSTACK_ACCESS_KEY
      - run:
          name: Run Tests on BrowserStack
          command: |
            export SELENIUM_REMOTE_URL="https://$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY@hub-cloud.browserstack.com/wd/hub"
            robot -d results tests/
      - store_artifacts:
          path: results
          destination: test-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - setup
      - test
      - test_remote

