version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3
  python: circleci/python@1.4.0

jobs:
  test_local:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - python/install-packages:
          pkg-manager: pip
          pip-dependencies: "robotframework robotframework-seleniumlibrary"
      - run:
          name: "Run Tests on Local Chrome"
          command: |
            robot -v BROWSER:chrome -d results tests/

  test_remote:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependencies: "robotframework robotframework-seleniumlibrary"
      - run:
          name: "Run Tests on Multiple Remote Browsers"
          command: |
            robot -v BROWSER:chrome -d results tests/
            robot -v BROWSER:firefox -d results tests/
            robot -v BROWSER:opera -d results tests/
            robot -v BROWSER:edge -d results tests/
            robot -v BROWSER:safari -d results tests/

  store_artifacts:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/results
          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - test_local
      - test_remote
      - store_artifacts:
          requires:
            - test_local
            - test_remote
