version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test_local:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      #- run:
      #    name: Install necessary system dependencies for browsers
      #    command: sudo apt-get update && sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 libxt6 libasound2
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Local Chrome Headless"
          command: |
            mkdir -p results/local/chrome
            export REMOTE_URL=None
            export BROWSER=Chrome
            export RUN_REMOTE=False
            robot -v browser_type:${BROWSER} -v REMOTE_URL:${REMOTE_URL} -v run_remote:${RUN_REMOTE} -d results/local/chrome tests/
      - store_artifacts:
          path: results/local/chrome
          destination: test-reports/local/chrome


  test_remote_chrome:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Chrome"
          command: |
            mkdir -p results/remote/chrome
            export REMOTE_URL="https://appium.tdc.tricentis-cloud.com:443/v0/403b52aad7e54e5fae88576008b3b6ad/wd/hub"
            export BROWSER=Chrome
            export RUN_REMOTE=True
            #echo "Using REMOTE_URL=${REMOTE_URL}"
            #echo "Using BROWSER=${BROWSER}"
            #echo "Using RUN_REMOTE=${RUN_REMOTE}"
            robot -v browser_type:${BROWSER} -v REMOTE_URL:${REMOTE_URL} -v run_remote:${RUN_REMOTE} -d results/remote/chrome tests/
      - store_artifacts:
          path: results/remote/chrome
          destination: test-reports/remote/chrome

  test_remote_firefox:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Firefox"
          command: |
            mkdir -p results/remote/firefox
            export REMOTE_URL="https://appium.tdc.tricentis-cloud.com:443/v0/403b52aad7e54e5fae88576008b3b6ad/wd/hub"
            export BROWSER=Firefox
            export RUN_REMOTE=True
            robot -v browser_type:${BROWSER} -v REMOTE_URL:${REMOTE_URL} -v run_remote:${RUN_REMOTE} -d results/remote/firefox tests/
      - store_artifacts:
          path: results/remote/firefox
          destination: test-reports/remote/firefox

  test_remote_edge:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Edge"
          command: |
            mkdir -p results/remote/edge
            export REMOTE_URL="https://appium.tdc.tricentis-cloud.com:443/v0/403b52aad7e54e5fae88576008b3b6ad/wd/hub"
            export BROWSER=Edge
            export RUN_REMOTE=True
            robot -v browser_type:${BROWSER} -v REMOTE_URL:${REMOTE_URL} -v run_remote:${RUN_REMOTE} -d results/remote/edge tests/
      - store_artifacts:
          path: results/remote/edge
          destination: test-reports/remote/edge

  test_remote_opera:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Opera"
          command: |
            mkdir -p results/remote/opera
            export REMOTE_URL="https://appium.tdc.tricentis-cloud.com:443/v0/403b52aad7e54e5fae88576008b3b6ad/wd/hub"
            export BROWSER=Opera
            export RUN_REMOTE=True
            robot -v browser_type:${BROWSER} -v REMOTE_URL:${REMOTE_URL} -v run_remote:${RUN_REMOTE} -d results/remote/opera tests/
      - store_artifacts:
          path: results/remote/opera
          destination: test-reports/remote/opera
          
  test_remote_safari:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Safari"
          command: |
            mkdir -p results/remote/safari
            export REMOTE_URL="https://appium.tdc.tricentis-cloud.com:443/v0/403b52aad7e54e5fae88576008b3b6ad/wd/hub"
            export BROWSER=Safari
            export RUN_REMOTE=True
            robot -v browser_type:${BROWSER} -v REMOTE_URL:${REMOTE_URL} -v run_remote:${RUN_REMOTE} -d results/remote/safari tests/
      - store_artifacts:
          path: results/remote/safari
          destination: test-reports/remote/safari

workflows:
  version: 2
  build:
    jobs:
      - test_local
      - test_remote_chrome
      - test_remote_firefox
      - test_remote_edge
      #- test_remote_opera
      - test_remote_safari
