version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test_local:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Install necessary system dependencies for browsers
          command: sudo apt-get update && sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 libxt6 libasound2
      - run:
          name: Install Robot Framework and SeleniumLibrary
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Local Chrome"
          command: |
            mkdir -p results/local
            robot -v BROWSER:Chrome -d results/local tests/
      - store_artifacts:
          path: results/local
          destination: test-reports/local

  test_remote:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Install necessary system dependencies for browsers
          command: sudo apt-get update && sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 libxt6 libasound2
      - run:
          name: Install Opera and OperaDriver
          command: |
            set -e  # Stop the script on errors

            # Install dependencies for fetching the latest versions
            sudo apt-get update && sudo apt-get install -y curl jq

            # Fetch the latest OperaDriver version dynamically
            LATEST_OPERA_DRIVER_URL=$(curl -s https://api.github.com/repos/operasoftware/operachromiumdriver/releases/latest | jq -r '.assets[] | select(.name | test("operadriver_linux64.zip")) | .browser_download_url')
            wget -q -O operadriver.zip $LATEST_OPERA_DRIVER_URL
            unzip operadriver.zip -d operadriver
            sudo mv operadriver/operadriver_linux64/operadriver /usr/local/bin/

            # Fetch the latest Opera Browser version dynamically
            LATEST_OPERA_DEB_URL=$(curl -s https://ftp.opera.com/ftp/pub/opera/desktop/ | grep -oP 'href="\K[^"]+' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/$' | sort -V | tail -n 1 | xargs -I{} echo "https://ftp.opera.com/ftp/pub/opera/desktop/{}/linux/opera-stable_current_amd64.deb")
            wget -q -O opera.deb $LATEST_OPERA_DEB_URL
            sudo dpkg -i opera.deb || sudo apt-get install -yf

            # Verify installation
            if ! command -v operadriver &> /dev/null; then
              echo "OperaDriver installation failed!"
              exit 1
            fi
            if ! dpkg -l | grep -q opera; then
              echo "Opera installation failed!"
              exit 1
            fi
      - run:
          name: Install Edge and Edge WebDriver
          command: |
            wget -q -O microsoft.gpg https://packages.microsoft.com/keys/microsoft.asc
            sudo apt-key add microsoft.gpg
            sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
            sudo apt-get update
            sudo apt-get install -y microsoft-edge-stable
            EDGE_DRIVER_VERSION=$(wget -qO- https://msedgedriver.azureedge.net/LATEST_STABLE | grep -oP '^[0-9.]+')
            wget -q -O msedgedriver.zip https://msedgedriver.azureedge.net/$EDGE_DRIVER_VERSION/edgedriver_linux64.zip
            unzip msedgedriver.zip -d msedgedriver
            sudo mv msedgedriver/msedgedriver /usr/local/bin/
      - run:
          name: Install Robot Framework and SeleniumLibrary
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Multiple Remote Browsers"
          command: |
            robot -v BROWSER:Chrome -d results/remote tests/
            robot -v BROWSER:Firefox -d results/remote tests/
            robot -v BROWSER:Opera -d results/remote tests/
            robot -v BROWSER:Edge -d results/remote tests/
            robot -v BROWSER:Safari -d results/remote tests/
      - store_artifacts:
          path: results/remote
          destination: test-reports
  test_mac:
    macos:
      xcode: "15.4.0"
    steps:
      - checkout
      - run:
          name: Install necessary system dependencies
          command: brew install geckodriver chromedriver operadriver
      - run:
          name: Install Robot Framework and SeleniumLibrary
          command: pip3 install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Multiple Browsers"
          command: |
            robot -v BROWSER:Safari -d results/safari tests/
      - store_artifacts:
          path: results/remote
          destination: test-reports

  store_artifacts:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: results
          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - test_local
      - test_remote
      - store_artifacts:
          requires:
            - test_local
            - test_remote
