version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test_local:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      #- run:
      #    name: Install necessary system dependencies for browsers
      #    command: sudo apt-get update && sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 libxt6 libasound2
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Local Chrome Headless"
          command: |
            mkdir -p results/local/chrome
            robot -v BROWSER:Chrome -v RUN_REMOTE:False -d results/local/chrome tests/
      - store_artifacts:
          path: results/local/chrome
          destination: test-reports/local/chrome


  test_remote_chrome:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Chrome"
          command: |
            mkdir -p results/remote/chrome
            export REMOTE_URL=https://chrome_111.0.5563.64@tricentis-us-sny-0.tdc-host.tricentis-cloud.com:9091/v0/403b52aad7e54e5fae88576008b3b6ad/wd/hub
            robot --loglevel DEBUG -v BROWSER:Chrome -v PLATFORM:Windows -v BROWSER_VERSION:latest -v REMOTE_URL:${REMOTE_URL} -v RUN_REMOTE:True -d results/remote/chrome tests/
      - store_artifacts:
          path: results/remote/chrome
          destination: test-reports/remote/chrome

  test_remote_firefox:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Firefox"
          command: |
            mkdir -p results/remote/firefox
            export REMOTE_URL=https://firefox_110.0@tricentis-us-sny-0.tdc-host.tricentis-cloud.com:9091/v0/403b52aad7e54e5fae88576008b3b6ad/wd/hub
            robot --loglevel DEBUG -v BROWSER:Firefox -v PLATFORM:Windows -v BROWSER_VERSION:latest -v REMOTE_URL:${REMOTE_URL} -v RUN_REMOTE:True -d results/remote/firefox tests/
      - store_artifacts:
          path: results/remote/firefox
          destination: test-reports/remote/firefox

  test_remote_edge:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Edge"
          command: |
            mkdir -p results/remote/edge
            export REMOTE_URL=https://microsoftedge_111.0.1661.41@tricentis-us-sny-0.tdc-host.tricentis-cloud.com:9091/v0/403b52aad7e54e5fae88576008b3b6ad/wd/hub
            robot --loglevel DEBUG -v BROWSER:Edge -v PLATFORM:Windows -v BROWSER_VERSION:latest -v REMOTE_URL:${REMOTE_URL} -v RUN_REMOTE:True -d results/remote/edge tests/
      - store_artifacts:
          path: results/remote/edge
          destination: test-reports/remote/edge

  test_remote_opera:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary selenium==4.2.0
      - run:
          name: "Run Tests on Opera"
          command: |
            mkdir -p results/remote/opera
            export REMOTE_URL=https://opera_97.0.4719.28@tricentis-us-sny-0.tdc-host.tricentis-cloud.com:9091/v0/403b52aad7e54e5fae88576008b3b6ad/wd/hub
            robot --loglevel DEBUG -v BROWSER:opera -v PLATFORM:Windows -v BROWSER_VERSION:latest -v REMOTE_URL:${REMOTE_URL} -v RUN_REMOTE:True -d results/remote/opera tests/
      - store_artifacts:
          path: results/remote/opera
          destination: test-reports/remote/opera

  test_remote_safari:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Packages
          command: pip install robotframework robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Safari"
          command: |
            mkdir -p results/remote/safari
            export REMOTE_URL=https://safari_16.6@tricentis-us-sny-0.tdc-host.tricentis-cloud.com:9091/v0/403b52aad7e54e5fae88576008b3b6ad/wd/hub
            robot --loglevel DEBUG -v BROWSER:Safari -v PLATFORM:MAC -v BROWSER_VERSION:latest -v REMOTE_URL:${REMOTE_URL} -v RUN_REMOTE:True -d results/remote/safari tests/
      - store_artifacts:
          path: results/remote/safari
          destination: test-reports/remote/safari

  #testing!
  test_mac:
    macos:
      xcode: "15.4.0"
    steps:
      - checkout
      - run:
          name: Install Robot Framework and SeleniumLibrary
          command: |
            pip3 install robotframework robotframework-seleniumlibrary selenium
      - run:
          name: Enable SafariDriver
          command: |
            sudo safaridriver --enable
      - run:
          name: Enable Safari Remote Automation
          command: |
            osascript enable_safari_automation.applescript
      - run:
          name: "Run Tests on Safari-Browser (MAC)"
          command: |
            mkdir -p results/safari
            robot -v BROWSER:Safari -d results/safari tests/
      - store_artifacts:
          path: results/safari
          destination: test-reports/safari

workflows:
  version: 2
  build:
    jobs:
      - test_local
      - test_remote_chrome
      - test_remote_firefox
      - test_remote_edge
      - test_remote_opera
      - test_remote_safari
      #- test_mac
