version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8
  python: circleci/python@1.2.3

jobs:
  test_local:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Install necessary system dependencies for browsers
          command: sudo apt-get update && sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 libxt6 libasound2
      - python/install-packages:
          pkg-manager: pip
          packages: 
            - robotframework
            - robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Local Chrome Headless"
          command: |
            mkdir -p results/local/chrome
            robot -v BROWSER:Chrome -v RUN_REMOTE:False -d results/local/chrome tests/
      - store_artifacts:
          path: results/local/chrome
          destination: test-reports/local/chrome

  test_remote:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      #- browser-tools/install-browser-tools
      - python/install-packages:
          pkg-manager: pip
          packages: 
            - robotframework
            - robotframework-seleniumlibrary
      - run:
          name: "Run Tests on Multiple Remote Browsers"
          command: |
            mkdir -p results/remote
            export BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME
            export BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY
            export REMOTE_URL=https://${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}@hub-cloud.browserstack.com/wd/hub
            # Run tests on BrowserStack remote browsers
            robot -v BROWSER:Chrome -v PLATFORM:Windows -v BROWSER_VERSION:latest -v REMOTE_URL:${REMOTE_URL} -v RUN_REMOTE:True -d results/remote/chrome tests/
            robot -v BROWSER:Firefox -v PLATFORM:Windows -v BROWSER_VERSION:latest -v REMOTE_URL:${REMOTE_URL} -v RUN_REMOTE:True -d results/remote/firefox tests/
            robot -v BROWSER:Edge -v PLATFORM:Windows -v BROWSER_VERSION:latest -v REMOTE_URL:${REMOTE_URL} -v RUN_REMOTE:True -d results/remote/edge tests/
            robot -v BROWSER:Safari -v PLATFORM:macOS -v BROWSER_VERSION:latest -v REMOTE_URL:${REMOTE_URL} -v RUN_REMOTE:True -d results/remote/safari tests/
      - store_artifacts:
          path: results/remote
          destination: test-reports/remote

  #testing!
  test_mac:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: Install Robot Framework and SeleniumLibrary
          command: |
            pip3 install robotframework robotframework-seleniumlibrary selenium
      - run:
          name: Enable SafariDriver
          command: |
            sudo safaridriver --enable
      - run:
          name: Enable Safari Remote Automation
          command: |
            osascript enable_safari_automation.applescript
      - run:
          name: "Run Tests on Safari-Browser (MAC)"
          command: |
            mkdir -p results/safari
            robot -v BROWSER:Safari -d results/safari tests/
      - store_artifacts:
          path: results/safari
          destination: test-reports/safari

workflows:
  version: 2
  build:
    jobs:
      - test_local
      - test_remote
      #- test_mac
