version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  setup:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            pip install --upgrade pip
            pip install "packaging<21.0,>=20.4"
            pip install robotframework
            pip install robotframework-seleniumlibrary
            pip install chromedriver-autoinstaller

  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            pip install --upgrade pip
            pip install "packaging<21.0,>=20.4"
            pip install robotframework
            pip install robotframework-seleniumlibrary
            pip install chromedriver-autoinstaller
      - run:
          name: Install and Verify ChromeDriver
          command: |
            python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"
            which chromedriver
            chromedriver --version
      - run:
          name: Run Tests
          command: |
            robot -d results tests/
      - store_artifacts:
          path: results
          destination: test-results

  test_remote:
    docker:
      - image: selenium/standalone-chrome
      - image: selenium/standalone-firefox
      - image: selenium/standalone-opera
      - image: selenium/standalone-edge
    steps:
      - checkout
      - run:
          name: Install BrowserStack Local
          command: |
            wget https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
            unzip BrowserStackLocal-linux-x64.zip
            mkdir -p ~/bin
            mv BrowserStackLocal ~/bin/BrowserStackLocal
            export PATH=$PATH:~/bin
      - run:
          name: Start BrowserStack Local
          background: true
          command: |
            ~/bin/BrowserStackLocal $BROWSERSTACK_ACCESS_KEY
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            pip install "packaging<21.0,>=20.4"
            pip install robotframework
            pip install robotframework-seleniumlibrary
      - run:
          name: Run Tests on BrowserStack
          command: |
            export SELENIUM_REMOTE_URL="https://$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY@hub-cloud.browserstack.com/wd/hub"
            robot -d results tests/
      - store_artifacts:
          path: results
          destination: test-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - setup
      - test
      - test_remote
